[package]
name = "balls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ac-ffmpeg = "0.18.1"
lazy_static = "1.4.0"
macroquad = "0.3.25"
